kafka:
  brokers: "localhost:9092"
  auth_protocol: PLAINTEXT

  in_topics: saimiris-targets
  in_group_id: saimiris-agent-wbmwwp9vna

  out_enable: true
  out_topic: saimiris-results

agent:
  id: wbmwwp9vna
